; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Bing Search"
#define MyAppVersion "1.0.17+19"
#define MyAppPublisher "Bonfire" 
#define MyAppExeName "bing_search_automation_example.exe"
#define MyAppServiceName "Rewards.exe"
#define MyAppAssocName MyAppName + " File"  
#define MyAppAssocExt ".rew"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt   
#define MyAppRootDir "C:\\Users\\Bonfire\\Projects\\Flutter\\bing_search_automation\\example"
#define MyAppReleaseDir "build\windows\x64\runner\Release"
#define Timestamp GetDateTimeString('yyyymmdd.hhnnss', '-', ':')
#define MyPassword 'bonfire'

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BCDEEA46-B524-4318-8FCA-42A00BF6688B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppPublisher}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
;ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
;ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequired=admin
OutputDir={#MyAppRootDir}\release
OutputBaseFilename={#MyAppName}({#MyAppVersion})_{#Timestamp}
SetupIconFile={#MyAppRootDir}\windows\runner\resources\app_icon.ico
SolidCompression=yes
WizardStyle=modern
Password={#MyPassword}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Executables and other DLLs
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; These are pre-defined generated DLLs for imported packages
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\flutter_local_notifications_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\permission_handler_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\screen_retriever_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\tray_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\url_launcher_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\webview_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\WebView2Loader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\window_manager_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion

; These DLL files are for MS Visual Runtime C++

Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\libcrypto-1_1-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\libssl-1_1-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion  
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\vcruntime140_1.dll"; DestDir: "{app}"; Flags: ignoreversion
; Copy data folder and its contents
Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "{#MyAppRootDir}\{#MyAppReleaseDir}\Templates\*"; DestDir: "{app}\Templates"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]


[UninstallRun]


[Code]
var
  DeleteDocChecked: Boolean;
  CleanupChecked: Boolean;
  InstallServiceCheckbox: TNewCheckBox;
const
  UninstSiteURL = 'https://mycdis.com/sirius-pos';
  UninstPassword = 'bonfire';

// This will displayed during installation
procedure InitializeWizard;
begin
  WizardForm.PasswordEdit.Text := '';
end;

function DeleteFileIfExists(const FileName: string): Boolean;
begin
  if FileExists(FileName) then
  begin
    Result := DeleteFile(FileName);
    if not Result then
      MsgBox('Failed to delete file: ' + FileName, mbError, MB_OK);
  end
  else
    Result := True;
end;


function AskPassword(const Prompt: string; var Password: string): Boolean;
var
  Form: TForm;
  Edit: TEdit;
  OKButton, CancelButton: TButton;
begin
  Result := False;
  Form := CreateCustomForm;
  try
    Form.Caption := 'Uninstall Password';
    Form.Width := ScaleX(300);
    Form.Height := ScaleY(150);
    Form.Position := poScreenCenter;

    Edit := TEdit.Create(Form);
    Edit.Parent := Form;
    Edit.Left := ScaleX(20);
    Edit.Top := ScaleY(30);
    Edit.Width := ScaleX(250);
    Edit.PasswordChar := '*';
    Edit.Text := '';
    Edit.TabOrder := 0;

    with TLabel.Create(Form) do
    begin
      Parent := Form;
      Caption := Prompt;
      Left := Edit.Left;
      Top := Edit.Top - ScaleY(20);
      Width := Edit.Width;
    end;

    OKButton := TButton.Create(Form);
    OKButton.Parent := Form;
    OKButton.Caption := 'OK';
    OKButton.ModalResult := mrOk;
    OKButton.Left := ScaleX(100);
    OKButton.Top := Edit.Top + ScaleY(40);
    OKButton.Width := ScaleX(75);

    CancelButton := TButton.Create(Form);
    CancelButton.Parent := Form;
    CancelButton.Caption := 'Cancel';
    CancelButton.ModalResult := mrCancel;
    CancelButton.Left := OKButton.Left + OKButton.Width + ScaleX(10);
    CancelButton.Top := OKButton.Top;
    CancelButton.Width := ScaleX(75);

    Form.ActiveControl := Edit;

    if Form.ShowModal = mrOk then
    begin
      Password := Edit.Text;
      Result := True;
    end;
  finally
    Form.Free;
  end;
end;

function InitializeUninstall(): Boolean;
var
  ResultCode: Integer;
  Response: Integer;  
  TargetLockFile: string;
  TargetAppFile: string;
  EnteredPassword: string;
begin
  if not AskPassword('Enter password to uninstall:', EnteredPassword) then
  begin
    // User pressed Cancel
    Result := False;
    Exit;
  end;

  if EnteredPassword <> UninstPassword then
  begin
    MsgBox('Incorrect password. Uninstallation will be aborted.', mbCriticalError, MB_OK);
    Result := False;
    Exit;
  end;

  // Check if the app is running
  if ShellExec('', 'tasklist', '/FI "IMAGENAME eq kiosk.exe"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) and (ResultCode = 0) then
  begin
    Response := MsgBox('Kiosk appears to be running. Do you want to close it before uninstalling?', mbConfirmation, MB_YESNO);
    if Response = IDYES then
    begin
      Exec('taskkill', '/F /IM kiosk.exe', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    end
    else
    begin
      MsgBox('Uninstallation canceled because the application is still running.', mbError, MB_OK);
      Result := False;
      Exit;
    end;
  end;

  Result := True;
end;

procedure InitializeUninstallProgressForm();
var
  UninstallPage: TNewNotebookPage;
  UninstallButton: TNewButton;
  CleanupCheckbox: TNewCheckBox;
  FeedbackCheckbox: TNewCheckBox;
  OriginalPageNameLabel: string;
  OriginalPageDescriptionLabel: string;
  OriginalCancelButtonEnabled: Boolean;              
  OriginalCancelButtonModalResult: Integer;
  ctrl: TWinControl;
begin
  if not UninstallSilent then
  begin
    ctrl := UninstallProgressForm.CancelButton;
    UninstallButton := TNewButton.Create(UninstallProgressForm);
    UninstallButton.Parent := UninstallProgressForm;
    UninstallButton.Left := ctrl.Left - ctrl.Width - ScaleX(10);
    UninstallButton.Top := ctrl.Top;
    UninstallButton.Width := ctrl.Width;
    UninstallButton.Height := ctrl.Height;
    UninstallButton.TabOrder := ctrl.TabOrder;
    UninstallButton.Caption := 'Uninstall';
    UninstallButton.ModalResult := mrOK;    
    UninstallProgressForm.CancelButton.TabOrder := UninstallButton.TabOrder + 1;
    UninstallPage := TNewNotebookPage.Create(UninstallProgressForm);
    UninstallPage.Notebook := UninstallProgressForm.InnerNotebook;
    UninstallPage.Parent := UninstallProgressForm.InnerNotebook;
    UninstallPage.Align := alClient;
    UninstallProgressForm.InnerNotebook.ActivePage := UninstallPage;
 
    ctrl := UninstallProgressForm.StatusLabel;
    with TNewStaticText.Create(UninstallProgressForm) do
    begin
      Parent := UninstallPage;
      Top := ctrl.Top;
      Left := ctrl.Left;
      Width := ctrl.Width;
      Height := ctrl.Height;
      AutoSize := False;
      ShowAccelChar := False;
      Caption := '';
    end;
 
    CleanupCheckbox := TNewCheckBox.Create(UninstallProgressForm);
    CleanupCheckbox.Parent := UninstallPage;
    CleanupCheckbox.Top := ctrl.Top + ScaleY(30);
    CleanupCheckbox.Left := ctrl.Left;
    CleanupCheckbox.Width := ScaleX(300);
    CleanupCheckbox.Caption := 'Remove application data, logs, and settings';
    CleanupCheckbox.Checked := True;

    FeedbackCheckbox := TNewCheckBox.Create(UninstallProgressForm);
    FeedbackCheckbox.Parent := UninstallPage;
    FeedbackCheckbox.Top := ctrl.Top + ScaleY(50);
    FeedbackCheckbox.Left := ctrl.Left;
    FeedbackCheckbox.Width := ScaleX(300);
    FeedbackCheckbox.Caption := 'Delete .Kiosk folder from Documents';
    FeedbackCheckbox.Checked := True;
 
    OriginalPageNameLabel := UninstallProgressForm.PageNameLabel.Caption;
    OriginalPageDescriptionLabel := UninstallProgressForm.PageDescriptionLabel.Caption;
    OriginalCancelButtonEnabled := UninstallProgressForm.CancelButton.Enabled;
    OriginalCancelButtonModalResult := UninstallProgressForm.CancelButton.ModalResult;
              
    UninstallProgressForm.PageNameLabel.Caption := 'Cleanup Sirius Kiosk';
    UninstallProgressForm.PageDescriptionLabel.Caption := 'Sirius Kiosk will be uninstalled from your computer. You may also choose to remove all associated data, logs, and settings.';
    UninstallProgressForm.CancelButton.Enabled := True;
    UninstallProgressForm.CancelButton.ModalResult := mrCancel;
 
    if UninstallProgressForm.ShowModal = mrCancel then Abort;
 
    UninstallButton.Visible := False;   
    UninstallProgressForm.PageNameLabel.Caption := OriginalPageNameLabel;
    UninstallProgressForm.PageDescriptionLabel.Caption := OriginalPageDescriptionLabel;
    UninstallProgressForm.CancelButton.Enabled := OriginalCancelButtonEnabled;
    UninstallProgressForm.CancelButton.ModalResult := OriginalCancelButtonModalResult;
 
    UninstallProgressForm.InnerNotebook.ActivePage := UninstallProgressForm.InstallingPage;
 
    if CleanupCheckbox.Checked then
    begin
      CleanupChecked:=True;
    end else
    begin
      CleanupChecked:=False;
    end;
    if FeedbackCheckbox.Checked then
    begin
      DeleteDocChecked:=True;
    end else
    begin
      DeleteDocChecked:=False;
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
  ErrorCode: Integer;
  UnlockPath: string;
begin
  if CurUninstallStep = usUninstall then
  begin
    // Delete all logs
    DelTree(ExpandConstant('{app}\data\.logs'), True, True, True);   
    
    if CleanupChecked then
    begin
      // Delete folder in app data
      //DelTree(ExpandConstant('{userappdata}\Bonfire Technologies & Solutions Corp'), True, True, True);
    end;

    if DeleteDocChecked then
    begin
      DelTree(ExpandConstant('{userdocs}\.Kiosk'), True, True, True);
    end;
  end;
  if CurUninstallStep = usDone then
  begin  
    DelTree(ExpandConstant('{app}'), False, True, True);
    ShellExec('', UninstSiteURL, '', '', SW_SHOW, ewNoWait, ErrorCode);
  end;
end;

