// List of predefined programming-related search terms
final List<String> keywords = [
  "Flutter app development",
  "Dart programming tutorial",
  "What is JavaScript?",
  "Python vs Java",
  "How to build a website",
  "Best coding practices",
  "Object-oriented programming explained",
  "Introduction to SQL",
  "How to use REST API",
  "GraphQL vs REST API",
  "Best IDEs for coding",
  "What is machine learning?",
  "Artificial intelligence programming",
  "Kotlin vs Java for Android",
  "C++ memory management",
  "How to start programming",
  "Best resources to learn coding",
  "What is recursion in programming?",
  "Understanding data structures",
  "What is an algorithm?",
  "Functional programming basics",
  "Best programming languages 2025",
  "How to debug code",
  "Unit testing in software development",
  "What is continuous integration?",
  "CI/CD pipeline explained",
  "Git vs SVN",
  "Best Git workflow practices",
  "How to use Docker",
  "Introduction to Kubernetes",
  "What is cloud computing?",
  "AWS vs Google Cloud vs Azure",
  "Introduction to Firebase",
  "How to use Supabase",
  "What is WebAssembly?",
  "How to write efficient SQL queries",
  "NoSQL vs SQL databases",
  "What is blockchain technology?",
  "Understanding smart contracts",
  "What is Solidity programming?",
  "Introduction to Rust programming",
  "Go programming for beginners",
  "Best Python libraries for data science",
  "How to use OpenAI API",
  "What is Web3 development?",
  "How to build a chatbot?",
  "Natural language processing tutorial",
  "Cybersecurity best practices",
  "How to prevent SQL injection",
  "Best tools for frontend development"
];
